trigger: none

queue:
  name: Hosted Ubuntu 1604

variables:
  # shared-variables group MUST contain: AZML_WORKSPACE, AZML_SUBID, AZML_RESGRP
  - group: shared-variables
  - name: AZML_DATAPATH
    value: titanic-data

steps:
- task: UsePythonVersion@0
  displayName: Use Python 3.6
  inputs:
    versionSpec: '3.6'
    addToPath: true 

- bash: |
    pip3 install -r requirements.txt
  workingDirectory: aml
  displayName: Install pip package requirements

- task: AzureCLI@1
  displayName: Start AML data prep script
  inputs:
    azureSubscription: $(AZML_SUBID)
    scriptLocation: inlineScript
    inlineScript: python3 prep-data.py
    workingDirectory: aml/titanic