#
# SAMPLE FILE - Make a copy of this with your values in!
#

# Change to the name of your ACR instance
registryPrefix: changeme.azurecr.io/

# Leave blank if not using DNS with your ingress
# If you have enabled the HTTP routing add on you may set the DNS zone here
domainSuffix: batcomputer.changeme.region.aksapp.io

# Change if not using AKS with HTTP routing add on, otherwise ignore
ingressClass: addon-http-application-routing

# Leave blank if you haven't set up cert-manager, and HTTPS will not be used
cmCertIssuer: 

# Model API settings, change image and modelVersion as required
api:
  image: batcomputer-model-api
  replicas: 1
  imagePullPolicy: Always
  modelVersion: 1